// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

interface Env {
    BACKEND?: string;
    DEFAULT_BACKEND?: string;
    CUSTOM_BACKEND?: string;
    LOCK_BACKEND?: boolean;
    REMOTE_CONFIG?: string;
    CHUNK_COUNT?: string;
    DB?: D1Database;
    /** 短链服务是否启用，由运行时适配层根据仓储可用性注入 */
    SHORT_URL_ENABLED?: boolean;
    /** 短链管理页访问密钥；未配置时禁止进入管理页 */
    SHORT_URL_KEY?: string;

    ORCA_ROUTER_URL?: string;
    ORCA_ROUTER_TOKEN?: string;
    ORCA_ROUTER_MODEL?: string;
}

